&blueprint
//---------------------------------------------------------------------------------------
// Method description...
// 
// Params:
//   arg1: 
//
// Return Params:
//   rarg1: 
//
// Returns: 
//
// Notes:     
// Examples:  
// See:       
//---------------------------------------------------------------------------------------

() 
  [
      SystemLib.print_screen("HOLA AMIGOS DE YUTUB")
  ]